version: "3.4"
services:
  frontend:
    build: ./frontend
    ports: 
      - 80:80
  backend:
    build: ./backend
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - G_CLIENT_ID
      - G_CLIENT_SECRET
      - G_REFRESH_TOKEN
      - G_REDIRECT_URL
      - G_TARGET
    ports:
      - 4000:4000
  db:
    build: ./db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5433:5432
